
#
# PHP Dependencies
#
FROM composer:1.7 as vendor

COPY database/ database/

COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

#
# application
#
FROM chaosxy/php:7.4.gd-cron-redis-supervisor as app

WORKDIR /var/www

RUN apt-get --allow-releaseinfo-change update && apt-get install -y \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
USER www

COPY --chown=www:www . /var/www

COPY --from=vendor /app/vendor/ /var/www/vendor/

#

# Add laravel schedule job
COPY --chown=www:www ./docker/start.sh /usr/bin/start.sh
COPY ./docker/laravel-schedule /etc/cron.d/laravel-schedule
COPY --chown=www:www .env.example /var/www/.env

RUN crontab /etc/cron.d/laravel-schedule

RUN chmod -R 0777 /var/www/bootstrap/ && chmod -R 0777 /var/www/public/ && chmod +x /usr/bin/start.sh && chmod a+rw /var/www/.env 

# Config supervisor to manager queue job
# RUN touch /var/log/supervisor.log
COPY ./docker/laravel-worker.conf /etc/supervisor/conf.d/laravel-worker.conf

USER root
ENTRYPOINT ["start.sh"]
