
#
# PHP Dependencies
#
FROM composer:1.7 as vendor

COPY database/ database/

COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

#
# application
#
FROM chaosxy/php:gd-cron-redis-supervisor as app

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY --chown=www:www . /var/www

COPY --from=vendor /app/vendor/ /var/www/vendor/

# Add laravel schedule job
COPY ./docker/laravel-schedule /etc/cron.d/laravel-schedule
RUN chmod 0644 /etc/cron.d/laravel-schedule
# Apply cron job
RUN crontab /etc/cron.d/laravel-schedule

RUN chmod -R 0777 /var/www/bootstrap/

# Config supervisor to manager queue job
RUN touch /var/log/supervisor.log
COPY ./docker/laravel-worker.conf /etc/supervisor/conf.d/laravel-worker.conf
RUN touch /var/run/supervisor.sock && chmod 777 /var/run/supervisor.sock
RUN supervisord -c /etc/supervisor/supervisord.conf

USER www

#
# Build nginx image
#
FROM nginx:stable-alpine as nginx

COPY ./public/ /var/www/public/
